postgres:
  container_name: gin-rest-api-example-postgres
  environment:
    - POSTGRES_PASSWORD=password
  image: postgres
  volumes:
    - /tmp/gin-postgres-data:/var/lib/postgresql/data
  ports:
    - 5437:5432
redis:
  container_name: gin-rest-api-example-redis
  image: redis
  command: redis-server --requirepass password
  volumes:
    - /tmp/gin-redis-data:/data
  ports:
    - 6378:6379
